version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    # Disable all pull requests for github-actions
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    # Disable all pull requests for npm
    open-pull-requests-limit: 0
